#!/usr/bin/env groovy
def appName = 'shipitclicker'
def dockerfile = 'chapter7/Dockerfile'
def registry = 'https://registry-1.docker.io/'
def appVersion = '0.5.0'
def getSemVer(appVersion, commitHash) {
      "${appVersion}+${env.BUILD_ID}.${commitHash}"
}
def getImageName(appName, appVersion, commitHash) {
  withCredentials([[$class: 'UsernamePasswordMultiBinding',
    credentialsId: 'shipit.dockerhub.id',
    usernameVariable: 'dh_user',
    passwordVariable: 'dh_password']]) {
      "${dh_user}/${appName}:${getSemVer(appVersion, commitHash)}"
  }
}
def getTarget() {
  env.BRANCH_NAME == 'staging' ? 'staging' : 'prod'
}
def shortCommit
pipeline {
  agent any
  stages {
    stage('build') {
      steps {
        checkout scm
        script {
          shortCommit = sh(
            returnStdout: true, 
            script: "git log -n 1 --pretty=format:'%h'").trim()
          docker.withRegistry(registry, 'shipit.dockerhub.id') {
            def image = docker.build(
              getImageName(appName, appVersion, shortCommit),
              "-f ${dockerfile} --network host ./chapter9"
            )
            image.push()
            }
          }
      }
    }
    stage('deploy') {
      when {
        anyOf {
          branch 'master'
          branch 'staging'
        }
      }
      environment {
          target = getTarget()
          image = getImageName(appName, appVersion, shortCommit)
      }
      steps {
        echo "BRANCH_NAME is ${env.BRANCH_NAME}"
        echo "Deploying to ${getTarget()}"
        withCredentials([[$class: 'UsernamePasswordMultiBinding',
          credentialsId: 'github',
          usernameVariable: 'githubUsername',
          passwordVariable: 'githubToken']]) {
            sh 'echo Target: $target Image: $image GitHub User: $githubUsername'
          }
      }
    }
  }
}
