LABEL “version”=”1.1.2-test” 

LABEL “description”=” Development environment container for testing the newest security patch. Not for production release yet” 

LABEL “security.txt”=”https://respository.example.com/my_project/security.txt” 
 
