---
version: '3'
services:
  shipit-clicker-web-v4:
    image: ${DOCKER_IMAGE:-dockerfordevelopers/shipitclicker:0.4.0}
    build: .
    environment:
        - APP_ID=shipit-clicker-v4
        - OPENAPI_SPEC=/api/v1/spec
        - OPENAPI_ENABLE_RESPONSE_VALIDATION=false
        - PORT=3000
        - LOG_LEVEL=${LOG_LEVEL:-info}
        - REQUEST_LIMIT=100kb
        - REDIS_HOST=${REDIS_HOST:-redis}
        - REDIS_PORT=${REDIS_PORT:-6379}
        - SESSION_SECRET=${SESSION_SECRET:-mySecret-v4}
    ports:
        - "${PORT:-3008}:3000"
    networks:
      - private-redis-shipit-clicker-v4
    links:
      - redis
    depends_on:
      - redis

  redis:
    command: ["redis-server", "--appendonly", "yes"]
    image: redis:5-alpine3.10
    volumes:
      - redis-data-shipit-clicker:/data
    networks:
      - private-redis-shipit-clicker-v4

volumes:
  redis-data-shipit-clicker: {}

networks:
  private-redis-shipit-clicker-v4:
